### ISSUE TITLE
Blank lines makes indentation detect nesting incorrectly

### ISSUE THREAD

**Issue by beelzebielsk** [ds26gte/neoscmindent#4]
This racket program gets indented incorrectly.

```racket
#lang racket

(provide (all-defined-out))

(define class-1%
  (class object%
    (inspect #f)

    (init size)))

(define class-2%
  (class object%
    (inspect #f)

    (init size)))
```

The second define gets indented as if it were contained within the body of `class-1%`. Removing all the blank lines from `class-1%` stops the error from happening.

**Comment by ds26gte** [comment]
Fix pushed in 3cb51cc

**Comment by beelzebielsk** [comment]
It doesn't seem to fix it. I pulled the new commits, I ran it on a clean neovim where that's the only plugin, so there's no chance of a weird interaction.
